[package]
name = "pcli"
version = "0.1.0"
edition = "2021"
default-run = "pcli"

[[bin]]
name = "pcli"
path = "src/main.rs"

[dependencies]
clang = { path = "clang" }
clap = { version = "4.1.10", features = ["derive"] }
crossterm = "0.26.1"
